# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-02 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency', models.FloatField(default=0, null=True, verbose_name='Latency')),
                ('city_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_from', to='cities_light.City', verbose_name='City from')),
                ('city_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='cities_light.City', verbose_name='City to')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='latency',
            unique_together=set([('city_from', 'city_to')]),
        ),
    ]
